### ISSUE TITLE
Design > Toolbar component seems to be problematic with https pages

### ISSUE THREAD

**Issue by tvby** [madalinoprea/magneto-debug#46] opened 2016-02-11 22:36 UTC
when trying to view design handles on pages served over https get a mixed content warning in chrome devtools console indicating the page was loaded over https, but requested an insecure XMLHttpRequest endpoint
https://mydomain.com/sheep_debug/design/viewHandle/default/store/1/area/frontend/ . This request has been blocked; the content must be served over HTTPS.

**Comment by madalinoprea** [comment] 2016-02-12 14:13
Hi @tvby,

I've pushed a bigger update few minutes ago. Can you check if this still is happening?

I cannot reproduce this issue. My secure and unsecure domains are both configured over https.

Thanks,
Mario

**Comment by madalinoprea** [comment] 2016-02-19 08:31
Closing for now. Please reopen if you see same issue on latest release.

**Closed by madalinoprea** 2016-02-19 08:31 UTC

**Comment by tvby** [comment] 2016-02-22 15:13
The problem no longer exist. It just now if you are on a https page and access anything through the toolbar the result will switch over to http instead of leaving you on the https page

**Comment by madalinoprea** [comment] 2016-02-23 15:46
Previous version was generating url for ajax calls on http even when current page was rendered on https.  Due to this error, ajax call on https pages were not executed.

Current version doesn't contain any ajax call on the actual toolbar. So problem solved :)

All its urls are generated based on current unsecure domain. I don't see any reason why we should stick to https protocol when clicking on some menu item on toolbar. Magento out of the box switches to http when customers goes away from checkout (that's on https) to some category page.

Thinks that we might reconsider:
- Should we always use secure domain for toolbar urls? Because these requests contain sensitive information we should be handled similar to '/account/' or '/checkout/' urls. This will make a lot of sense when we will have some sort of authentication that will allows to 'safely' deploy the extension on external environments.

Is this making any sense?

**Comment by tvby** [comment] 2016-02-29 12:39
Yes I understand your reasoning now.
