### ISSUE TITLE
Can't see in frontend

### ISSUE THREAD

**Issue by R11baka** [madalinoprea/magneto-debug#23] opened 2013-06-21 07:14 UTC
I cant see in frontend.Magento 1.7.0.2.Use not default store,and theme.In backend all ok.
No included any js file

**Comment by mr-jingles** [comment] 2015-07-10 19:11
i think the problem is that one file gets linked to two destinations:

in the modman file:

#frontend
design/layout/debug.xml         app/design/frontend/base/default/layout/debug.xml 
design/template/debug           app/design/frontend/base/default/template/debug
# admin
design/layout/debug.xml         app/design/adminhtml/base/default/layout/debug.xml
design/template/debug           app/design/adminhtml/base/default/template/debug

frontend does not get linked... i am usin bragento installer

**Comment by mr-jingles** [comment] 2015-07-10 20:04
this one works with bragento installer: https://github.com/mr-jingles/magneto-debug.git

**Comment by madalinoprea** [comment] 2016-02-03 09:52
Closing this. 

I don't have an idea why reported issue occurred. Usually we have several suspects (I should probably document those):
- Magento is not configured to accept symlinked template files
- Apache is not configured to follow symlinks (see Option FollowSymLinks)

**Closed by madalinoprea** 2016-02-03 09:52 UTC

**Comment by r-martins** [comment] 2016-02-03 10:38
Just try to see if it's loaded in html but not shown.
There's a bug in new versions of magento, that is easy to correct. The <head> js/css selector finds more than one element. You just need to fix that line if this is the problem.
