### ISSUE TITLE
Exception in Magento 1.9.2.4

### ISSUE THREAD

**Issue by ThomasNegeli** [madalinoprea/magneto-debug#68] opened 2016-03-03 10:08 UTC
# Extension Version
1.5.0
# Magento Version
1.9.2.4
# Exception
a:5:{i:0;s:48:"Block ANONYMOUS_41 is already marked as rendered";i:1;s:4648:"#0 /vagrant/vendor/madalinoprea/magneto-debug/code/Debug/Model/Observer.php(261): Sheep_Debug_Model_Block->startRendering(Object(Mage_Adminhtml_Block_Template))
#1 /vagrant/html/app/code/core/Mage/Core/Model/App.php(1358): Sheep_Debug_Model_Observer->onBlockToHtml(Object(Varien_Event_Observer))
#2 /vagrant/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Sheep_Debug_Model_Observer), 'onBlockToHtml', Object(Varien_Event_Observer))
#3 /vagrant/html/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('core_block_abst...', Array)
#4 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(906): Mage::dispatchEvent('core_block_abst...', Array)
#5 /vagrant/html/app/code/core/Mage/Adminhtml/Block/System/Store/Tree.php(135): Mage_Core_Block_Abstract->toHtml()
#6 /vagrant/html/app/design/adminhtml/default/default/template/system/store/tree.phtml(81): Mage_Adminhtml_Block_System_Store_Tree->renderWebsite(Object(Aitoc_Aitquantitymanager_Model_Rewrite_FrontCoreWebsite))
#7 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(241): include('/vagrant/html/a...')
#8 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#9 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#10 /vagrant/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#11 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#12 /vagrant/html/app/code/core/Mage/Adminhtml/Block/System/Store/Store.php(78): Mage_Core_Block_Abstract->toHtml()
#13 /vagrant/html/app/design/adminhtml/default/default/template/system/store/container.phtml(36): Mage_Adminhtml_Block_System_Store_Store->getGridHtml()
#14 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(241): include('/vagrant/html/a...')
#15 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#16 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#17 /vagrant/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#18 /vagrant/html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#19 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#20 /vagrant/html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#21 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#22 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#23 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#24 /vagrant/html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#25 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(241): include('/vagrant/html/a...')
#26 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#27 /vagrant/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#28 /vagrant/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#29 /vagrant/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#30 /vagrant/html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#31 /vagrant/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#32 /vagrant/html/app/code/core/Mage/Adminhtml/controllers/System/StoreController.php(60): Mage_Core_Controller_Varien_Action->renderLayout()
#33 /vagrant/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_StoreController->indexAction()
#34 /vagrant/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#35 /vagrant/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#36 /vagrant/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#37 /vagrant/html/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#38 /vagrant/html/index.php(83): Mage::run('', 'store')
#39 {main}";s:3:"url";s:78:"/index.php/backoffice/system_store/index/key/274106fb194fa00797bd5e72d02c5439/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by sandermangel** [comment] 2016-03-03 12:08
Hi @ThomasNegeli already reported this via https://github.com/madalinoprea/magneto-debug/issues/66

**Comment by madalinoprea** [comment] 2016-03-03 17:52
Thanks, @ThomasNegeli . 

We're going to close this issue as dupe of #66

**Comment by ThomasNegeli** [comment] 2016-03-15 15:26
Still the same problem with Version 1.6.0.
Problem occurs when I go to the store config in the backend. The other backend parts seem to work.

**Comment by madalinoprea** [comment] 2016-03-15 15:55
Hi @ThomasNegeli ,


Can you add an updated stack trace? Version 1.6.0 contained some updates that would ..

Oh shit.. probably Aitoc_Aitquantitymanager_Model_Rewrite_FrontCoreWebsite creates one block instance to recursively render a node tree and its childs.

I'll reopened this issue. No clue to address it but it least we can remove throw exception.

**Comment by madalinoprea** [comment] 2016-03-15 16:19
@ThomasNegeli , please check release 1.6.1. I've pushed that few minutes ago.

**Closed by madalinoprea** 2016-03-15 16:19 UTC
